workflows:
  flutter-workflow:
    name: YourTurn Flutter Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      cancel_previous_builds: true
    environment:
      # android_signing:
        # Add your Android signing configuration here when ready
        # - keystore_reference
      # ios_signing:
        # Add your iOS signing configuration here when ready
        # distribution_type: app_store
        # bundle_identifier: com.tendimensions.yourturn
      vars:
        # Environment variables (configure these in Codemagic dashboard under Environment variables):
        # Create a group called 'firebase_credentials' with:
        # - FIREBASE_SERVICE_ACCOUNT (JSON from Firebase Console → Project Settings → Service Accounts)
        # - FIREBASE_ANDROID_APP_ID
        # - FIREBASE_IOS_APP_ID
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - firebase_credentials
      flutter: 3.27.0
      xcode: latest
      java: 21
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Flutter doctor
        script: |
          flutter doctor -v
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test || echo "No tests found or tests failed, continuing build..."
        ignore_failure: true
      - name: Flutter build APK
        script: |
          flutter build apk --release
      - name: Flutter build iOS (unsigned)
        script: |
          flutter build ios --release --no-codesign
      - name: Build iOS IPA (Ad Hoc)
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/ios/Runner.xcarchive \
            archive
          xcodebuild -archivePath $CM_BUILD_DIR/build/ios/Runner.xcarchive \
            -exportArchive \
            -exportPath $CM_BUILD_DIR/build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist
        ignore_failure: true
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # Firebase App Distribution
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_ANDROID_APP_ID
          groups:
            - testers
          artifact_type: apk
        ios:
          app_id: $FIREBASE_IOS_APP_ID
          groups:
            - testers
          artifact_type: ipa
      
      email:
        recipients:
          - $NOTIFICATION_EMAIL
        notify:
          success: true
          failure: true

  flutter-dev-workflow:
    name: YourTurn Flutter Dev Build (Manual)
    max_build_duration: 45
    instance_type: mac_mini_m1
    triggering:
      events: []  # Manual trigger only - no automatic builds
    environment:
      flutter: 3.27.0
      xcode: latest
      java: 21
      cocoapods: default
      vars:
        # Environment variables configured in Codemagic dashboard
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - firebase_credentials
    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Flutter doctor
        script: |
          flutter doctor -v
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter build APK (debug)
        script: |
          flutter build apk --debug
      - name: Flutter build iOS (debug, unsigned)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphoneos/*.app
    publishing:
      # Firebase App Distribution for dev builds
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_ANDROID_APP_ID
          groups:
            - dev-testers
          artifact_type: apk
      email:
        recipients:
          - $NOTIFICATION_EMAIL
        notify:
          success: true
          failure: true