workflows:
  flutter-workflow:
    name: YourTurn Flutter Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
      cancel_previous_builds: true
    environment:
      flutter: 3.27.0
      xcode: latest
      cocoapods: default
      vars:
        # ---- App identifiers ----
        ANDROID_PACKAGE_NAME: com.tendimensions.yourturn
        IOS_BUNDLE_ID: com.tendimensions.yourturn

        # ---- Firebase App Distribution ----
        FIREBASE_APP_ID_ANDROID: $FIREBASE_ANDROID_APP_ID
        FIREBASE_APP_ID_IOS: $FIREBASE_IOS_APP_ID

        # ---- iOS export method for ad-hoc device installs ----
        EXPORT_METHOD: ad-hoc   # options: development | ad-hoc | enterprise | app-store

      # Pull secret groups you'll define in Codemagic UI → Environment variables
      groups:
        # - android_signing
        - ios_signing
        - firebase_credentials
      
      java: 21
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.pub-cache
        - ios/Pods
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Run unit tests
        script: |
          echo "Running Flutter unit tests..."
          flutter test --reporter compact
          echo "✅ All tests passed!"
        ignore_failure: true

      - name: Set up Android keystore
        script: |
          # Ensure AndroidX is enabled
          cat >> "$CM_BUILD_DIR/android/gradle.properties" <<EOF
          android.useAndroidX=true
          android.enableJetifier=true
          EOF
          
          # ANDROID_KEYSTORE_BASE64, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > $CM_BUILD_DIR/android/app/keystore.jks

          cat > $CM_BUILD_DIR/android/key.properties <<EOF
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=keystore.jks
          EOF

      - name: Build Android APK (release)
        script: |
          flutter build apk --release --build-number="$PROJECT_BUILD_NUMBER"

      - name: Create release notes
        script: |
          echo "Build #$PROJECT_BUILD_NUMBER" > release_notes.txt
          echo "Branch: $CM_BRANCH" >> release_notes.txt
          echo "Commit: $(echo $CM_COMMIT | cut -c1-8)" >> release_notes.txt
          echo "" >> release_notes.txt
          
          # Debug: Check if CHANGELOG.md exists and show its location
          echo "Debug: Current directory: $(pwd)"
          echo "Debug: CHANGELOG.md exists: $(test -f "CHANGELOG.md" && echo "YES" || echo "NO")"
          if [ -f "CHANGELOG.md" ]; then
            echo "Debug: First 10 lines of CHANGELOG.md:"
            head -10 CHANGELOG.md
            echo ""

            echo "Latest Changes:" >> release_notes.txt
            echo "" >> release_notes.txt
            # Read from top until we hit "---" delimiter, skip first 2 lines (title and blank)
            # More robust version that handles different line ending formats
            sed '/^---$/q' CHANGELOG.md | sed '$d' | tail -n +3 >> release_notes.txt
          else
            echo "CHANGELOG.md not found, using default release notes" >> release_notes.txt
            echo "• Initial release" >> release_notes.txt
          fi
          
          echo "" >> release_notes.txt
          echo "Built on: $(date)" >> release_notes.txt
          echo "Created release notes file:"
          cat release_notes.txt

      - name: Build iOS IPA (manual signing)
        script: |
          # Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
          keychain initialize
          
          # Set up provisioning profiles from environment variables
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo ${CM_PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
          echo "Saved provisioning profile $PROFILE_PATH"
          
          # Set up signing certificate
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
          
          # Set up code signing settings on Xcode project
          xcode-project use-profiles
          
          # Build iOS IPA using the export options generated by Codemagic
          flutter build ipa \
            --release \
            --build-number="$PROJECT_BUILD_NUMBER" \
            --export-options-plist=/Users/builder/export_options.plist
          
          # List generated files for debugging
          echo "Generated files:"
          find build -name "*.ipa" -o -name "*.xcarchive" | head -10

    artifacts:
      - build/app/outputs/**/*.apk
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/**/*.ipa
      - flutter_drive.log

    publishing:
      # Firebase App Distribution
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_APP_ID_ANDROID
          groups:
            - yourturn-testers
          artifact_type: apk
        ios:
          app_id: $FIREBASE_APP_ID_IOS
          groups:
            - yourturn-testers
      
      email:
        recipients:
          - $NOTIFICATION_EMAIL
        notify:
          success: true
          failure: true
